//   https://en.cppreference.com/w/cpp/language/operator_precedence.html





               ///althoug its not clear >>

/*
| **Precedence** | **Operators**                                                                          | **Description**                                                                                                                    | **Associativity**                                             |               |               |
| -------------- | -------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- | ------------- | ------------- |
| 1              | `::`                                                                                   | Scope resolution                                                                                                                   | Left-to-right                                                 |               |               |
| 2              | `a++`, `a--`, `type()`, `a()`, `a[]`, `a->b`                                           | Postfix increment/decrement, functional cast, function call, subscript, member access                                              | Left-to-right                                                 |               |               |
| 3              | `++a`, `--a`, `+a`, `-a`, `!a`, `~a`, `(type)a`, `*a`, `&a`, `sizeof`, `new`, `delete` | Prefix inc/dec, unary plus/minus, logical NOT, bitwise NOT, casts, indirection, address-of, sizeof, memory allocation/deallocation | Right-to-left                                                 |               |               |
| 4              | `a.*b`, `a->*b`                                                                        | Pointer-to-member                                                                                                                  | Left-to-right                                                 |               |               |
| 5              | `*`, `/`, `%`                                                                          | Multiplication, division, remainder                                                                                                | Left-to-right                                                 |               |               |
| 6              | `+`, `-`                                                                               | Addition, subtraction                                                                                                              | Left-to-right                                                 |               |               |
| 7              | `<<`, `>>`                                                                             | Bitwise shift left/right                                                                                                           | Left-to-right                                                 |               |               |
| 8              | `<=>`                                                                                  | Three-way comparison (C++20)                                                                                                       | Left-to-right                                                 |               |               |
| 9              | `<`, `<=`, `>`, `>=`                                                                   | Relational operators                                                                                                               | Left-to-right                                                 |               |               |
| 10             | `==`, `!=`                                                                             | Equality operators                                                                                                                 | Left-to-right                                                 |               |               |
| 11             | `&`                                                                                    | Bitwise AND                                                                                                                        | Left-to-right                                                 |               |               |
| 12             | `^`                                                                                    | Bitwise XOR                                                                                                                        | Left-to-right                                                 |               |               |
| 13             | \`                                                                                     | \`                                                                                                                                 | Bitwise OR                                                    | Left-to-right |               |
| 14             | `&&`                                                                                   | Logical AND                                                                                                                        | Left-to-right                                                 |               |               |
| 15             | \`                                                                                     |                                                                                                                                    | \`                                                            | Logical OR    | Left-to-right |
| 16             | `?:`, `throw`, `=`, `+=`, `-=`, `*=`, `/=`, `%=`, `<<=`, `>>=`, `&=`, `^=`, \`         | =\`                                                                                                                                | Ternary conditional, throw, assignments, compound assignments | Right-to-left |               |
| 17             | `,`                                                                                    | Comma                                                                                                                              | Left-to-right                                                 |               |               |

*/