
-- doctor
CREATE TABLE EMPLOYEE (

  EMPLOYEE_ID NUMBER GENERATED ALWAYS AS IDENTITY
    (START WITH 100 INCREMENT BY 1)
    PRIMARY KEY,

  NAME VARCHAR2(50),

  TYPE VARCHAR2(50),

  SPECIALIZATION VARCHAR2(100),

  EXPERIENCE NUMBER(2),

  DATE_JOIN DATE,

  GENDER VARCHAR2(10),
  EMAIL VARCHAR2(50),
  PHONE_NUMBER VARCHAR2(20),

  SALARY NUMBER(10,2),

  DOMAIN VARCHAR2(50)
);
