-- Evaluators Table
CREATE TABLE EVALUATORS (
  EVAL_ID       NUMBER PRIMARY KEY,
  EVAL_NAME     VARCHAR2(30),
  DEPARTMENT    VARCHAR2(30),
  PHONE         NUMBER(10)
);

-- Teams Table
CREATE TABLE TEAMS (
  TEAM_ID        NUMBER PRIMARY KEY,
  TEAM_NAME      VARCHAR2(20),
  TEAM_LEADER    VARCHAR2(30),
  STUDENT_COUNT  NUMBER,
  ROLL_NO        NUMBER(8),
  EVAL_ID        NUMBER,

  CONSTRAINT FK_TEAM_EVAL
    FOREIGN KEY (EVAL_ID)
    REFERENCES EVALUATORS(EVAL_ID)
);

-- Insert records into table Evaluatero
INSERT ALL
  INTO EVALUATORS VALUES (101, 'RAJESH', 'CSE', 9876543210)
  INTO EVALUATORS VALUES (102, 'Nitin', 'IT', 9876501234)
  INTO EVALUATORS VALUES (103, 'ANITA', 'ECE', 9812345678)
SELECT 1 FROM DUAL;

-- insert record for the ta
INSERT ALL
  INTO TEAMS VALUES (1, 'A1', 'ARJUN', 10, 24241001, 101)
  INTO TEAMS VALUES (2, 'A2', 'MOHIT', 11, 24241421, 101)
  INTO TEAMS VALUES (3, 'B1', 'NEHA', 9, 24242015, 102)
  INTO TEAMS VALUES (4, 'B2', 'RAHUL', 8, 24242108, 103)
SELECT 1 FROM DUAL;

-- join
--^ Which evaluator is guiding each PBL team?
SELECT
  E.EVAL_ID,
  E.EVAL_NAME,
  E.DEPARTMENT,
  T.TEAM_ID,
  T.TEAM_NAME,
  T.TEAM_LEADER,
  T.STUDENT_COUNT
FROM EVALUATORS E
INNER JOIN TEAMS T
ON E.EVAL_ID = T.EVAL_ID; -- join condition


-- INFO
-- Teams *-1 Evaluatero
